language: c++
compiler: gcc

notification:
- email: false

befor_install:
- sudo apt-get update -qq

install:
- sudo apt-get install -qq cppcheck qt5-default qtbase5-dev

script:
- cppcheck --quiet --error-exitcode=1 .
- mkdir build && cd build
- cmake .. && make
- cd src
- ./travis_test

