language: c++

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
          env: COMPILER=g++-4.9
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
          packages:
            - clang-3.6
          env: COMPILER=clang++-3.6

notification:
- email: false

befor_install:
- sudo apt-get update -qq

install:
- sudo apt-get install -qq cppcheck qt5-default qtbase5-dev

script:
- cppcheck --quiet --error-exitcode=1 .
- mkdir build && cd build
- cmake -DCMAKE_CXX_COMPILER=$COMPILER .. && make
- cd src
- ./travis_test
